# Generated by Django 3.2.16 on 2023-07-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_follow_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='fallowing',
            new_name='following',
        ),
    ]
